### ISSUE TITLE
Distributed Part-Seeding

### ISSUE THREAD

**Issue by r0kk3rz** [pipermerriam/ipfs-persistence-consortium#1]
I had a similar idea for a service that can help persist IPFS objects which I think can improve on what you've started here in a number of ways.
1. Make a particular IPFS hash a token that all persistance consortium clients will pin, the content of the hash doesn't have to have any real meaning but then you can use findprovs with that hash to find other persistance consortium clients on the DHT.
2. Get around the trust factor by only seeding certain blocks of any given set. You don't really need to worry about the legality of the content if you're only storing a random 10% of the blocks, and so instead of having to have trusted peers you can have it be a trustless decentralised network of services.
3. Make each server have some kind of webservice or RPC so a client program can be made which can query the DHT for servers, and ask them to persist an object, and watch findprovs so it knows when the object is fully uploaded.
4. Instead of pinning whole files or individual blocks, just use the IPFS cache. This will give each object a limited amount of time to be sent around the network, but it also means you don't have to worry about running out of harddrive space and the service can be run completely hands off.

**Comment by pipermerriam** [comment]
This is meant to be a stop-gap solution until SWARM is live

Since it's intentionally backed by trust, most of the problems you outline don't apply.  The `findprovs` functionality is however something I was unaware of and opens up some interesting options.
