### ISSUE TITLE
Missing file creation in README

### ISSUE THREAD

**Issue by llopv** [pipermerriam/ipfs-persistence-consortium#2]
In the section [How to ask others to mirror](https://github.com/pipermerriam/ipfs-persistence-consortium#how-to-ask-others-to-mirror-your-ipfs-content), only the directory is created, but not the `manifest-1.json` file, and most importantly, it does not explain what to put into the file.

**Comment by pipermerriam** [comment]
Thanks for reporting this.

A manifest file should be in the following format.

``` javascript
[
    "QmYwxuzozCBSD3FLP5Rg1pAXA4qjDtNrdGjyNzqEtr8TKu",
    "QmTrXyK24CAymWj5eATjxrisc8QaJocnGSY11BFFDEvqtH"
]
```

Just a simple json array of IPFS hashes.

```
```

**Comment by pipermerriam** [comment]
Added this to the README.
